\set ON_ERROR_STOP on

-- Clinic schema for Docker first-init (schema only, no seed data)

create table if not exists blood_type (
  id bigint primary key generated by default as identity,
  blood_type_full text not null check (blood_type_full in ('A+','B+','AB+','O+','A-','B-','AB-','O-')),
  blood_type text not null check (blood_type in ('A','B','AB','O')),
  rh_factor text not null check (rh_factor in ('Positive','Negative')),
  unique (blood_type, rh_factor)
);

create table if not exists department (
  id bigint primary key generated by default as identity,
  department_code text unique not null,
  department_name text not null,
  location_description text
);

create table if not exists doctor (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  doctor_code text unique not null,
  doctor_name text not null,
  gender text check (gender in ('Male','Female','Other')),
  specialty text,
  department_id bigint references department(id)
);

create table if not exists medicine (
  id bigint primary key generated by default as identity,
  medicine_code text unique not null,
  medicine_name text not null,
  generic_name text,
  medicine_type text not null check (medicine_type in ('Antifungals','Antihistamines','Antibiotics','Analgesics')),
  unit_cost numeric(12,2) not null default 0
);

create table if not exists treatment (
  id bigint primary key generated by default as identity,
  treatment_code text unique not null,
  treatment_name text not null,
  unit_cost numeric(12,2) not null default 0
);

create table if not exists fee (
  id bigint primary key generated by default as identity,
  fee_code text unique not null,
  fee_name text not null,
  fee_price numeric(12,2) not null default 0
);

create table if not exists medical_condition (
  id bigint primary key generated by default as identity,
  condition_code text unique not null,
  condition_name text not null,
  description text
);

create table if not exists patient (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  patient_code text unique not null,
  patient_name text not null,
  gender text check (gender in ('Male','Female','Other')),
  date_of_birth date not null,
  blood_type_id bigint references blood_type(id)
);

create table if not exists visit (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  visit_code text unique not null,
  patient_id bigint not null references patient(id),
  visit_type text not null check (visit_type in ('IPD','OPD')),
  reported_symptoms text,
  blood_pressure text,
  height numeric(6,2),
  weight numeric(6,2),
  temperature numeric(5,2),
  read_only boolean not null default false
);

create table if not exists appointed_doctor (
  id bigint primary key generated by default as identity,
  visit_id bigint not null references visit(id),
  appointed_doctor_code text unique not null
);

create table if not exists appointed_doctor_line (
  id bigint primary key generated by default as identity,
  appointed_doctor_id bigint not null references appointed_doctor(id),
  doctor_id bigint not null references doctor(id),
  notes text
);

create table if not exists prescription_chart (
  id bigint primary key generated by default as identity,
  visit_id bigint not null references visit(id),
  prescription_chart_code text unique not null
);

create table if not exists prescription_chart_line (
  id bigint primary key generated by default as identity,
  prescription_chart_id bigint not null references prescription_chart(id),
  medicine_id bigint not null references medicine(id),
  quantity numeric(10,2) not null,
  dosage_notes text
);

create table if not exists treatment_chart (
  id bigint primary key generated by default as identity,
  visit_id bigint not null references visit(id),
  treatment_chart_code text unique not null
);

create table if not exists treatment_chart_line (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  treatment_chart_id bigint not null references treatment_chart(id),
  treatment_id bigint not null references treatment(id),
  quantity numeric(10,2) not null default 1,
  notes text
);

create table if not exists diagnosis_chart (
  id bigint primary key generated by default as identity,
  visit_id bigint not null references visit(id),
  diagnosis_chart_code text unique not null
);

create table if not exists diagnosis_chart_line (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  diagnosis_chart_id bigint not null references diagnosis_chart(id),
  medical_condition_id bigint not null references medical_condition(id)
);

create table if not exists patient_bill (
  id bigint primary key generated by default as identity,
  bill_code text unique not null,
  visit_id bigint not null references visit(id),
  tax numeric(14,2) not null default 7
);

create table if not exists patient_bill_line (
  id bigint primary key generated by default as identity,
  bill_header_id bigint not null references patient_bill(id),
  charge_type text not null check (charge_type in ('Treatment','Medicine','Fee')),
  treatment_chart_line_id bigint references treatment_chart_line(id),
  prescription_chart_line_id bigint references prescription_chart_line(id),
  fee_id bigint references fee(id)
);

create table if not exists transaction_header (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  transaction_code text unique not null,
  bill_id bigint not null references patient_bill(id)
);

create table if not exists transaction_line (
  id bigint primary key generated by default as identity,
  transaction_header_id bigint not null references transaction_header(id),
  transaction_line_code text unique not null,
  amount numeric(14,2) not null,
  transaction_type text not null check (transaction_type in ('Cash','Credit Card','Debit Card','Digital Wallet'))
);
