\set ON_ERROR_STOP on

-- Add discount columns to invoice_line_item
ALTER TABLE invoice_line_item
  ADD COLUMN IF NOT EXISTS line_discount_percent numeric(5,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS line_discount_amount numeric(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS line_net_price numeric(14,2) NOT NULL DEFAULT 0.00;

-- Backfill: set line_net_price = extended_price where no discount
UPDATE invoice_line_item
  SET line_net_price = extended_price
  WHERE line_discount_amount = 0;

-- Add totals columns to invoice
ALTER TABLE invoice
  ADD COLUMN IF NOT EXISTS vat_rate numeric(5,4) NOT NULL DEFAULT 0.07,
  ADD COLUMN IF NOT EXISTS total_price numeric(14,2),
  ADD COLUMN IF NOT EXISTS total_discount numeric(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS vat_amount numeric(14,2);

-- Backfill: total_price = total_amount, vat_amount = vat where NULL
UPDATE invoice SET total_price = total_amount WHERE total_price IS NULL;
UPDATE invoice SET vat_amount = vat WHERE vat_amount IS NULL;

-- Create configuration table
CREATE TABLE IF NOT EXISTS configuration (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  key text UNIQUE NOT NULL,
  value text NOT NULL
);

-- Seed vat_percent
INSERT INTO configuration (key, value) VALUES ('vat_percent', '7') ON CONFLICT DO NOTHING;
